### ISSUE TITLE
Problem with keycloack in developer environment

### ISSUE THREAD

**Issue by igr** [SchweizerischeBundesbahnen/esta-webjs-2#71]
Hi! After updating to new stack, there is a small issue with the keycloack after the `ng serve`.

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://your_server.com') does not match the recipient window's origin ('null').
```

Previously when auth was not set (as it is a case with development environment), you could use the app. Now this is not possible anymore.

What would be the best solution to fix this so to use it in dev mode, w/o auth, like before?

**Comment by kreuzerk** [comment]
@igr Thanks a lot for mentioning this issue.

This problem occurs because we have adjusted the Auth configuration. The problem comes from the onLoad: 'check-sso' property on the KeyCloakInitOptions. 

To fix this issue you can just remove the onLoad option in your environment.ts and pass empty KeyCloakInitOptions. You can have a look at https://github.com/SchweizerischeBundesbahnen/esta-webjs-2/pull/72/files.

Notice: After adjusting environment.ts you may need to restart the app.
